package com.myhome.controllers.request;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Email;

/**
 * represents a request for a password reset link with email and token fields and
 * newPassword field, intended to be used by users to reset their account passwords.
 * Fields:
 * 	- email (String): in the ForgotPasswordRequest class is of type String and
 * represents a valid email address for the purpose of sending a password reset token
 * to the user.
 * 	- token (String): in the `ForgotPasswordRequest` class represents a unique
 * validation token generated by the system for the user's forgotten password request.
 * 	- newPassword (String): represents the password entered by the user for resetting
 * their account.
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
public class ForgotPasswordRequest {
  @Email
  public String email;
  public String token;
  public String newPassword;
}
