package com.myhome.controllers.request;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Email;

/**
 * represents a request for a password reset link with email and token fields, and
 * newPassword field.
 * Fields:
 * 	- email (String): in the ForgotPasswordRequest class is a required string parameter
 * for entering the user's email address to receive a password reset token.
 * 	- token (String): in the ForgotPasswordRequest class is meant to hold a unique
 * validation token generated by the system for the user's forgot password request.
 * 	- newPassword (String): is a String object representing the password entered by
 * the user for resetting their account.
 */
@AllArgsConstructor
@NoArgsConstructor
@Data
public class ForgotPasswordRequest {
  @Email
  public String email;
  public String token;
  public String newPassword;
}
